-keep class com.macsense.ai.** { *; }
-keepclassmembers class * extends androidx.room.RoomDatabase { *; }
-keep class * extends androidx.room.RoomDatabase
-keep class * implements androidx.room.RoomDatabase
-keepclassmembers class * implements androidx.room.RoomDatabase { *; }
