package com.macsense.ai.sync

import kotlinx.serialization.Serializable

/**
 * A shareable project link for async collaboration.
 * Generated by the project owner; grants view, comment, or edit access
 * depending on [accessLevel].
 */
@Serializable
data class ProjectShareLink(
    val id: String,
    val projectId: String,
    val ownerUserId: String,
    val accessLevel: AccessLevel,
    val createdAt: Long,
    val expiresAt: Long? = null
) {
    enum class AccessLevel { VIEW_ONLY, COMMENT, PROPOSE_EDITS, FULL_EDIT }
}

/**
 * A comment anchored to a specific location in the project.
 * Location types let comments target sections, stems, lyric lines, or time ranges.
 */
@Serializable
data class ProjectComment(
    val id: String,
    val projectId: String,
    val authorUserId: String,
    val authorName: String,
    val anchor: CommentAnchor,
    val text: String,
    val createdAt: Long,
    val resolved: Boolean = false
) {
    @Serializable
    sealed class CommentAnchor {
        @Serializable
        data class SectionAnchor(val sectionId: String) : CommentAnchor()
        @Serializable
        data class StemAnchor(val sectionId: String, val stemLane: String) : CommentAnchor()
        @Serializable
        data class LyricAnchor(val sectionId: String, val lineIndex: Int) : CommentAnchor()
        @Serializable
        data class TimeRangeAnchor(val startSeconds: Double, val endSeconds: Double) : CommentAnchor()
    }
}

/**
 * A proposed edit submitted as a branch — like a Git PR for audio.
 * The owner reviews and merges or rejects.
 */
@Serializable
data class BranchProposal(
    val id: String,
    val projectId: String,
    val branchId: String,
    val proposerUserId: String,
    val proposerName: String,
    val title: String,
    val description: String,
    val createdAt: Long,
    val status: ProposalStatus = ProposalStatus.PENDING,
    val reviewedAt: Long? = null,
    val reviewerUserId: String? = null
) {
    enum class ProposalStatus { PENDING, MERGED, REJECTED, CHANGES_REQUESTED }
}

/**
 * Aggregates the collaboration state for a project.
 * Used by the UI to show comments, proposals, and access info.
 */
data class CollaborationState(
    val shareLink: ProjectShareLink?,
    val comments: List<ProjectComment>,
    val proposals: List<BranchProposal>,
    val pendingCommentCount: Int,
    val pendingProposalCount: Int
) {
    companion object {
        val EMPTY = CollaborationState(null, emptyList(), emptyList(), 0, 0)
    }
}
